### ISSUE TITLE
no captcha and db:seed errors

### ISSUE THREAD

**Issue by v1ct0r-LH** [brighton36/CoinPost#1]
In the registration form, i have a blank screen in place of the captcha

![slection_001](https://f.cloud.github.com/assets/2298609/2045987/46446942-8a00-11e3-9e1c-5d87f5c918ce.png)

the db:seed command fail :

```
rake db:seed --trace
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:abort_if_pending_migrations
Creating Category "Fashion"
Creating Category "Motors"
Creating Category "Computers & Gaming"
Creating Category "Electronics"
Creating Category "Collectibles & Art"
Creating Category "Home & Decor"
Creating Category "Entertainment"
Creating Category "Miscellaneous"
Creating Category "Services"
Creating Users
Creating Shipping Policies
Creating Return Policies...
Creating 200 expired itemsrake aborted!
No such file or directory - /usr/share/dict/words
/root/CoinPost/spec/factories/item.rb:95:in `initialize'
/root/CoinPost/spec/factories/item.rb:95:in `open'
/root/CoinPost/spec/factories/item.rb:95:in `create_seed_items'
/root/CoinPost/db/seeds.rb:45:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/delorean-2.1.0/lib/flux_capacitor.rb:7:in `time_travel_to'
/root/CoinPost/db/seeds.rb:43:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.9.1/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `block in load'
/var/lib/gems/1.9.1/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.9.1/gems/railties-3.2.14/lib/rails/engine.rb:525:in `load_seed'
/var/lib/gems/1.9.1/gems/activerecord-3.2.14/lib/active_record/railties/databases.rake:347:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:seed
```

**Comment by DaGitNah** [comment]
Can we instead use google's reCaptcha?

**Comment by brighton36** [comment]
If you want to code it - I'm fine  with that!

**Comment by DaGitNah** [comment]
I am new at ruby code so I did some googling. https://gurudathbn.wordpress.com/2015/01/22/google-recaptcha-with-ruby-on-rails-integration/
